name: Build Extension
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-bin meson gettext

      - name: Compile schemas
        run: glib-compile-schemas schemas/

      - name: Build extension
        run: |
          meson setup build
          ninja -C build
